'use client';
import {apiCall} from '../lib/google-client';

import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,BookOpen,Users,Clock,CheckCheck,RefreshCw,Download,LogOut,Monitor,Smartphone,Tablet,Activity,ShieldCheck,LoaderCircle,AlertCircle} from 'lucide-react';
import {pages} from '../lib/book';
type Stats={days:number;updatedAt:number;active:number;storage:'local'|'google-sheets';configured:boolean;totals:{sessions:number;visitors:number;readers:number;readingSeconds:number;avgSeconds:number;completed:number;incomplete:number;hottestPage:number;hottestSeconds:number};daily:{day:string;visits:number;visitors:number;readers:number}[];devices:{device:string;count:number}[];pages:{page:number;count:number;seconds:number;dropouts:number}[];recent:{visitor:string;createdAt:number;device:string;browser:string;platform:string;source:string;readingSeconds:number;started:number;lastPage:number;pagesRead:number;exited:boolean}[];};
const number=(n:number)=>new Intl.NumberFormat('th-TH').format(n);
const duration=(n:number)=>n>=60?`${Math.floor(n/60)} นาที ${Math.floor(n%60)} วิ`:`${Math.round(n)} วินาที`;
const thaiTime=(s:number,full=false)=>new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',...(full?{day:'numeric',month:'short'}:{}),hour:'2-digit',minute:'2-digit'}).format(new Date(s*1000));
const colors=['#dc8051','#839d7a','#e4bc67'];
export default function Dashboard({onBack,onExpired}:{onBack:()=>void;onExpired:()=>void}){
 const [days,setDays]=useState(7);const [data,setData]=useState<Stats|null>(null);const [busy,setBusy]=useState(true);const [error,setError]=useState('');const [loggingOut,setLoggingOut]=useState(false);const requestId=useRef(0);
 const load=useCallback(async()=>{const id=++requestId.current;setBusy(true);setError('');try{const res=await apiCall(`/api/admin/stats?days=${days}`,{cache:'no-store'});if(id!==requestId.current)return;if(res.status===401){onExpired();return;}const result=await res.json() as Stats & {error?:string};if(!res.ok)throw new Error(result.error);setData(result);}catch(e){if(id===requestId.current)setError(e instanceof Error?e.message:'โหลดข้อมูลไม่ได้');}finally{if(id===requestId.current)setBusy(false);}},[days,onExpired]);
 useEffect(()=>{load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load();},30000);return()=>{clearInterval(timer);requestId.current++;};},[load]);
 const logout=async()=>{setLoggingOut(true);try{const res=await apiCall('/api/admin/logout',{method:'POST'});if(!res.ok)throw new Error('ออกจากระบบไม่สำเร็จ กรุณาลองใหม่');onBack();}catch(e){setError(e instanceof Error?e.message:'ออกจากระบบไม่สำเร็จ');setLoggingOut(false);}};
 const exportCsv=()=>{if(!data)return;const rows=[['รหัสผู้ชม','เวลาเข้า (ไทย)','อุปกรณ์','เบราว์เซอร์','ระบบ','ที่มา','เริ่มอ่าน','หน้าที่เปิด','เวลาอ่าน (วินาที)'],...data.recent.map(v=>[v.visitor,thaiTime(v.createdAt,true),v.device,v.browser,v.platform,v.source,v.pagesRead===15?'อ่านจบ':'ยังไม่จบ',v.pagesRead,v.readingSeconds])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`little-shopper-visits-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const t=data?.totals;const chartDays=Array.from({length:days},(_,i)=>{const day=new Date(((data?.updatedAt??Date.now()/1000)+25200-(days-1-i)*86400)*1000).toISOString().slice(0,10);return {...(data?.daily.find(d=>d.day===day)??{visits:0,visitors:0,readers:0}),day};});
 const max=Math.max(4,...chartDays.map(d=>d.visits));const top=Math.ceil(max/4)*4;const coords=chartDays.map((d,i)=>`${40+i/(days-1)*630},${205-d.visits/top*170}`);const maxPage=Math.max(1,...(data?.pages.map(d=>d.seconds)??[1]));
 return <main className="dashboard">
  <header className="dash-nav"><button className="text-button" onClick={onBack}><ArrowLeft size={17}/> กลับไปหน้าหนังสือ</button><span className="dash-brand"><BookOpen size={19}/> little shopper <i>/</i><span>TEACHER'S CORNER</span></span><button className="text-button" onClick={logout} disabled={loggingOut}><LogOut size={16}/><span>{loggingOut?'กำลังออก…':'ออกจากระบบ'}</span></button></header>
  <div className="dash-content"><div className="dash-heading"><div><span className="eyebrow">THE STORY BEHIND THE READERS</span><h1>ทุกการอ่าน คือการเติบโต<span>✳</span></h1><p>ดูการเดินทางของนักช้อปตัวน้อย ผ่านสถิติการอ่านจริง</p></div><span className="active-pill"><i/>{number(data?.active??0)} คน กำลังใช้งาน</span></div>
  <div className="dash-filters"><div className="range-buttons" aria-label="ช่วงเวลาของสถิติ">{[7,30,90].map(d=><button key={d} className={days===d?'active':''} onClick={()=>setDays(d)} aria-pressed={days===d}>{d} วันล่าสุด</button>)}</div><div className="dash-actions"><button className="icon-button" aria-label="โหลดสถิติใหม่" title="โหลดสถิติใหม่" onClick={load} disabled={busy}><RefreshCw size={17} className={busy?'spin':''}/></button><button className="secondary-button" onClick={exportCsv} disabled={!data||busy}><Download size={15}/><span>ส่งออก 50 รายการล่าสุด</span></button></div></div>
  {error&&<div className="dash-error" role="alert"><AlertCircle size={19}/><span>{error}</span><button onClick={load}>ลองใหม่</button></div>}
  {busy&&!data?<div className="dash-loading"><LoaderCircle className="spin"/><p>กำลังรวบรวมเรื่องราวการอ่าน…</p></div>:data&&<>
   {!data.configured&&<div className="integration-notice"><ShieldCheck size={18}/><span>สถิตินี้ยังเก็บในเว็บเดิม · เชื่อม Google Sheets โดยวาง Web App URL ใน config.js</span></div>}
   <section className="metric-grid" aria-label="สถิติภาพรวม"><Metric icon={<Users size={21}/>} label="คนกดเริ่มอ่าน" value={number(t?.readers??0)} unit="คน" detail={`${number(t?.sessions??0)} รอบการอ่าน · นับเบราว์เซอร์ไม่ซ้ำ`} color="sage"/><Metric icon={<CheckCheck size={21}/>} label="คนอ่านจบ" value={number(t?.completed??0)} unit="คน" detail="คนที่เคยเปิดครบ 15 หน้าในรอบเดียว" color="peach"/><Metric icon={<BookOpen size={21}/>} label="คนยังอ่านไม่จบ" value={number(t?.incomplete??0)} unit="คน" detail="รวมคนที่ยังอ่านอยู่ · นับคนไม่ซ้ำ" color="butter"/><Metric icon={<Clock size={21}/>} label="ค้างหน้าไหนนานที่สุด" value={t?.hottestPage?String(t.hottestPage):'—'} unit={t?.hottestPage?'หน้า':''} detail={t?.hottestPage?`เวลาอ่านรวม ${duration(t.hottestSeconds)}`:'ยังไม่มีเวลาอ่านที่บันทึก'} color="lilac"/></section>
   <p className="analytics-definition">อ่านจบ = เปิดครบ 15 หน้า · คนเดิมที่อ่านจบภายหลังจะย้ายจากยังไม่จบไปฝั่งอ่านจบ · เวลาเฉลี่ยต่อรอบ {duration(t?.avgSeconds??0)}</p>
   <div className="dash-chart-grid"><section className="dash-panel visits-panel"><div className="panel-heading"><div><span className="mini-label">READING JOURNEY</span><h2>เริ่มอ่านกันเมื่อไรบ้าง?</h2></div><span className="chart-legend"><i/> จำนวนรอบการอ่าน</span></div><div className="line-chart"><svg viewBox="0 0 700 242" role="img" aria-label={`กราฟจำนวนรอบการอ่านรายวัน ${days} วัน รวม ${t?.sessions??0} ครั้ง`}>{Array.from({length:5},(_,i)=><g key={i}><line x1="40" x2="670" y1={35+i*42.5} y2={35+i*42.5} stroke="#e9e7df" strokeDasharray="4 5"/><text x="25" y={39+i*42.5} textAnchor="end">{top-i*top/4}</text></g>)}<defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e9a173" stopOpacity=".3"/><stop offset="100%" stopColor="#e9a173" stopOpacity=".02"/></linearGradient></defs><polygon points={`40,205 ${coords.join(' ')} 670,205`} fill="url(#chart-fill)"/><polyline points={coords.join(' ')} fill="none" stroke="#d88151" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>{chartDays.map((d,i)=>{const show=days===7||i===0||i===days-1||i%Math.ceil(days/6)===0;return <g key={d.day}>{show&&<text x={40+i/(days-1)*630} y="232" textAnchor="middle">{new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',timeZone:'Asia/Bangkok'}).format(new Date(d.day+'T00:00:00+07:00'))}</text>}{days===7&&<circle cx={40+i/(days-1)*630} cy={205-d.visits/top*170} r="4" fill="#d88151" stroke="#fff" strokeWidth="2"><title>{d.day}: {d.visits} ครั้ง</title></circle>}</g>;})}</svg>{!t?.sessions&&<p className="chart-empty">ยังไม่มีคนเริ่มอ่านในช่วงเวลานี้</p>}</div><div className="panel-footnote">อัปเดตอัตโนมัติทุก 30 วินาที · แสดงตามเวลาไทย</div></section>
   <section className="dash-panel devices-panel"><div className="panel-heading"><div><span className="mini-label">LITTLE READING SPACES</span><h2>อ่านจากที่ไหน?</h2></div><Monitor size={20}/></div><div className="device-list">{['มือถือ','แท็บเล็ต','คอมพิวเตอร์'].map((device,i)=>{const n=data.devices.find(d=>d.device===device)?.count??0;const percent=t?.sessions?Math.round(n/t.sessions*100):0;return <div className="device-row" key={device}><div className="device-label">{i===0?<Smartphone size={18}/>:i===1?<Tablet size={18}/>:<Monitor size={18}/>}<span>{device}</span><strong>{percent}%</strong></div><div className="device-track"><span style={{width:`${percent}%`,background:colors[i]}}/></div><small>{number(n)} รอบการอ่าน</small></div>;})}</div><p className="panel-footnote">จำแนกจากข้อมูลเบราว์เซอร์ของอุปกรณ์</p></section></div>
   <section className="dash-panel page-stats"><div className="panel-heading"><div><span className="mini-label">EVERY PAGE COUNTS</span><h2>ใช้เวลาอยู่หน้าไหนมากที่สุด?</h2></div><span className="muted">เวลาอ่านรวมแต่ละหน้า</span></div><div className="page-bars">{pages.map((p,i)=>{const stat=data.pages.find(d=>d.page===i+1);const sec=stat?.seconds??0;return <div className="page-bar-column" key={i} title={`หน้า ${i+1}: ${p.title} · ${duration(sec)} · เปิด ${stat?.count??0} รอบ · หยุดอ่านที่นี่ ${stat?.dropouts??0} รอบ`}><span>{Math.round(sec)} วิ</span><div><i style={{height:`${sec/maxPage*100}%`}}/></div><small>{i+1}</small></div>;})}</div><div className="panel-footnote">นับเวลาที่เปิดอ่านและใช้งาน · หยุดนับเมื่อซ่อนแท็บหรือไม่มีการใช้งาน 2 นาที · เลขด้านล่างคือหน้าหนังสือ</div>
   <div className="dropout-summary"><strong>หน้าที่คนหยุดอ่านบ่อย</strong>{data.pages.filter(p=>p.dropouts>0).sort((a,b)=>b.dropouts-a.dropouts).slice(0,3).map(p=><span key={p.page}>หน้า {p.page} · {p.dropouts} รอบ</span>)}{!data.pages.some(p=>p.dropouts>0)&&<span>ยังไม่มีข้อมูลการหยุดอ่าน</span>}<small>เฉพาะรอบที่ยังไม่จบและออกจากตัวอ่าน หรือไม่มีข้อมูลใหม่เกิน 30 นาที</small></div></section>
   <section className="dash-panel recent-panel"><div className="panel-heading"><div><span className="mini-label">RECENT LITTLE VISITORS</span><h2>รอยเท้าของนักอ่าน</h2></div><span className="table-count">ล่าสุด {data.recent.length} รายการ</span></div><div className="table-scroll"><table><thead><tr><th>ผู้ชมแบบไม่ระบุชื่อ</th><th>เวลาเข้าชม</th><th>อุปกรณ์</th><th>การอ่าน</th><th>เวลาอ่าน</th><th>สถานะ</th></tr></thead><tbody>{data.recent.map((v,i)=><tr key={`${v.visitor}-${v.createdAt}-${i}`}><td><span className="visitor-avatar"><Users size={15}/></span><span className="visitor-name">นักอ่าน #{v.visitor}</span></td><td>{thaiTime(v.createdAt,true)}</td><td>{v.device}<small>{v.browser} · {v.platform}</small></td><td>{v.pagesRead} / 15 หน้า</td><td>{duration(v.readingSeconds)}</td><td><span className={`status-tag ${v.pagesRead===15?'complete':v.started?'reading':''}`}>{v.pagesRead===15?'อ่านจบ':'ยังอ่านไม่จบ'}</span></td></tr>)}</tbody></table>{data.recent.length===0&&<div className="empty-table"><BookOpen size={28}/><strong>เรื่องราวการอ่านกำลังจะเริ่มต้น</strong><p>หลังกดเริ่มอ่าน สถิติจริงจะแสดงที่นี่</p></div>}</div></section>
  </>}
  <footer className="dash-footer"><span><ShieldCheck size={14}/> เก็บหลังกดเริ่มอ่านเท่านั้น · คนประมาณจากรหัสเบราว์เซอร์ · {data?.storage==='google-sheets'?'Google Sheets':'ยังไม่เชื่อมชีต'}</span><span>{data?`อัปเดต ${thaiTime(data.updatedAt)} น. (เวลาไทย)`:'ใช้ข้อมูลจริงจากการเข้าชม'}</span></footer></div>
 </main>;
}
function Metric({icon,label,value,unit,detail,color}:{icon:React.ReactNode;label:string;value:string;unit:string;detail:string;color:string}){return <div className="metric-card"><div className="metric-top"><span>{label}</span><span className={`metric-icon ${color}`}>{icon}</span></div><div className="metric-value">{value}<span>{unit}</span></div><p>{detail}</p></div>;}
